let y =('stella koomson');
console.log(y);
let x = (25);
console.log(x);
let q = 5 + 2;
console.log(q);
let a = 6-6;
console.log(a);
let e = 6/2;
console.log(e);
let r = 4*3;
console.log(r);
let b = 50%40;
console.log(b);
let fufu = true;
console.log(fufu);
let s = 4;
console.log(typeof(s));
let d = ("Stella");
console.log(typeof(d));
